// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvcdthcsztdlkhgvyxcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Y2R0aGNzenRkbGtoZ3Z5eGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDcyNDcsImV4cCI6MjA2NTQ4MzI0N30.hwvIdY62LVs8G2YRWoMYqoJhia8v7GpI3lZ8GG1Gn_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);